"""Dashboard services package."""

from src.observability.dashboard.services.automation_scenario_service import (
    AutomationScenario,
    build_runner_command,
    get_automation_scenario,
    get_pytest_targets,
    list_automation_scenarios,
)
from src.observability.dashboard.services.api_execution_adapter import (
    ApiExecutionAdapter,
    ExecutionResult,
    ExecutionStepResult,
    execute_plan_with_api_adapter,
)
from src.observability.dashboard.services.browser_execution_adapter import (
    BrowserDependencyError,
    BrowserExecutionAdapter,
    execute_plan_with_browser_adapter,
)
from src.observability.dashboard.services.execution_plan_service import (
    ExecutionPlan,
    ExecutionStep,
    build_execution_plan,
    get_execution_preset_steps,
)
from src.observability.dashboard.services.execution_result_report_service import (
    DEFAULT_EXECUTION_PLAN_ALLURE_RESULTS_DIR,
    DEFAULT_EXECUTION_PLAN_JUNIT_PATH,
    write_execution_result_allure_results,
    write_execution_result_junit_xml,
)
from src.observability.dashboard.services.execution_history_service import (
    DEFAULT_EXECUTION_HISTORY_PATH,
    ExecutionHistoryRecord,
    append_execution_history_record,
    build_execution_quality_trends,
    build_execution_history_record,
    load_execution_history_records,
    summarize_execution_history,
)
from src.observability.dashboard.services.test_design_service import (
    KnowledgeHit,
    SOURCE_TYPE_LABELS,
    TestDesignDraft,
    build_test_outline,
    format_knowledge_hit_title,
    generate_test_design_draft,
    get_default_query,
    get_focus_areas,
    get_scenario_blueprint,
    infer_source_type,
    normalize_source_type,
    retrieve_knowledge_hits,
)
from src.observability.dashboard.services.test_design_evaluation_service import (
    DEFAULT_TEST_DESIGN_GOLDEN_SET,
    DEFAULT_TEST_DESIGN_REPORT_DIR,
    TestDesignCaseResult,
    TestDesignEvaluationCase,
    TestDesignEvaluationReport,
    evaluate_test_design_case,
    load_test_design_golden_set,
    run_test_design_evaluation,
    write_test_design_evaluation_report,
)
from src.observability.dashboard.services.test_report_service import (
    ReportArtifact,
    TestExecutionSummary,
    discover_report_artifacts,
    get_default_junit_report_path,
    load_execution_summary,
    parse_junit_xml,
)
from src.observability.dashboard.services.test_design_templates import (
    FOCUS_OPTIONS,
    SCENARIO_BLUEPRINTS,
)

__all__ = [
    "AutomationScenario",
    "ApiExecutionAdapter",
    "BrowserDependencyError",
    "BrowserExecutionAdapter",
    "ExecutionPlan",
    "ExecutionResult",
    "ExecutionStep",
    "ExecutionStepResult",
    "ExecutionHistoryRecord",
    "FOCUS_OPTIONS",
    "KnowledgeHit",
    "build_execution_plan",
    "build_runner_command",
    "execute_plan_with_browser_adapter",
    "execute_plan_with_api_adapter",
    "get_automation_scenario",
    "get_execution_preset_steps",
    "get_pytest_targets",
    "list_automation_scenarios",
    "SCENARIO_BLUEPRINTS",
    "TestDesignDraft",
    "ReportArtifact",
    "SOURCE_TYPE_LABELS",
    "DEFAULT_TEST_DESIGN_GOLDEN_SET",
    "DEFAULT_TEST_DESIGN_REPORT_DIR",
    "DEFAULT_EXECUTION_HISTORY_PATH",
    "DEFAULT_EXECUTION_PLAN_ALLURE_RESULTS_DIR",
    "DEFAULT_EXECUTION_PLAN_JUNIT_PATH",
    "TestExecutionSummary",
    "TestDesignCaseResult",
    "TestDesignEvaluationCase",
    "TestDesignEvaluationReport",
    "append_execution_history_record",
    "build_execution_history_record",
    "build_execution_quality_trends",
    "build_test_outline",
    "discover_report_artifacts",
    "evaluate_test_design_case",
    "format_knowledge_hit_title",
    "generate_test_design_draft",
    "get_default_junit_report_path",
    "get_default_query",
    "get_focus_areas",
    "get_scenario_blueprint",
    "infer_source_type",
    "load_test_design_golden_set",
    "load_execution_summary",
    "load_execution_history_records",
    "normalize_source_type",
    "parse_junit_xml",
    "retrieve_knowledge_hits",
    "run_test_design_evaluation",
    "summarize_execution_history",
    "write_execution_result_allure_results",
    "write_test_design_evaluation_report",
    "write_execution_result_junit_xml",
]
