"""Service for running pytest automation scenarios from the FastAPI layer."""

from __future__ import annotations

import json
import subprocess
import sys
import uuid
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from src.observability.dashboard.services.automation_scenario_service import (
    get_automation_scenario,
)
from src.observability.dashboard.services.test_report_service import parse_junit_xml

REPO_ROOT = Path(__file__).resolve().parents[3]
RUNS_DIR = Path("reports") / "api-runs"


@dataclass(frozen=True)
class AutomationRunPaths:
    """Report paths generated by one automation run."""

    run_dir: str
    junitxml: str
    allure_results: str
    run_record: str


@dataclass(frozen=True)
class AutomationRunSummary:
    """Parsed test result counts for one automation run."""

    total: int
    passed: int
    failed: int
    errors: int
    skipped: int
    duration_seconds: float


def run_automation_scenario(
    scenario_id: str,
    *,
    project_root: Path | str = REPO_ROOT,
    timeout_seconds: int = 120,
) -> dict[str, Any]:
    """Run one built-in automation scenario and persist a JSON run record."""
    scenario = get_automation_scenario(scenario_id)
    root = Path(project_root)
    run_id = f"{scenario_id}-{uuid.uuid4().hex[:8]}"
    relative_run_dir = RUNS_DIR / run_id
    run_dir = root / relative_run_dir
    run_dir.mkdir(parents=True, exist_ok=True)

    paths = AutomationRunPaths(
        run_dir=str(relative_run_dir),
        junitxml=str(relative_run_dir / "junit.xml"),
        allure_results=str(relative_run_dir / "allure-results"),
        run_record=str(relative_run_dir / "run.json"),
    )
    command = [
        sys.executable,
        "scripts/run_automation_suite.py",
        "--scenario",
        scenario.scenario_id,
        "--junitxml",
        paths.junitxml,
        "--allure-results",
        paths.allure_results,
    ]

    started_at = _utc_now()
    try:
        completed = subprocess.run(
            command,
            cwd=root,
            capture_output=True,
            text=True,
            timeout=timeout_seconds,
            check=False,
        )
        return_code = completed.returncode
        stdout = completed.stdout
        stderr = completed.stderr
        timed_out = False
    except subprocess.TimeoutExpired as exc:
        return_code = -1
        stdout = exc.stdout if isinstance(exc.stdout, str) else ""
        stderr = exc.stderr if isinstance(exc.stderr, str) else ""
        stderr = f"{stderr}\nExecution timed out after {timeout_seconds} seconds".strip()
        timed_out = True

    finished_at = _utc_now()
    summary = _load_summary(root / paths.junitxml)
    status = _resolve_status(return_code, summary, timed_out)

    record: dict[str, Any] = {
        "run_id": run_id,
        "scenario_id": scenario.scenario_id,
        "scenario_name": scenario.name,
        "category": scenario.category,
        "status": status,
        "return_code": return_code,
        "timed_out": timed_out,
        "started_at": started_at,
        "finished_at": finished_at,
        "duration_seconds": _duration_seconds(started_at, finished_at),
        "command": command,
        "summary": None if summary is None else asdict(summary),
        "paths": asdict(paths),
        "stdout": _tail(stdout),
        "stderr": _tail(stderr),
    }
    _write_run_record(root / paths.run_record, record)
    return record


def list_automation_runs(project_root: Path | str = REPO_ROOT) -> list[dict[str, Any]]:
    """List persisted automation run records newest first."""
    root = Path(project_root)
    runs_root = root / RUNS_DIR
    if not runs_root.exists():
        return []

    records = [
        _read_run_record(path)
        for path in sorted(runs_root.glob("*/run.json"), key=lambda item: item.stat().st_mtime, reverse=True)
    ]
    return [record for record in records if record]


def get_automation_run(run_id: str, project_root: Path | str = REPO_ROOT) -> dict[str, Any]:
    """Return one persisted automation run record."""
    run_id = run_id.strip()
    if not run_id:
        raise ValueError("run_id is required")

    record_path = Path(project_root) / RUNS_DIR / run_id / "run.json"
    record = _read_run_record(record_path)
    if not record:
        raise FileNotFoundError(f"Automation run not found: {run_id}")
    return record


def _load_summary(junit_path: Path) -> AutomationRunSummary | None:
    if not junit_path.exists():
        return None
    parsed = parse_junit_xml(junit_path)
    return AutomationRunSummary(
        total=parsed.total,
        passed=parsed.passed,
        failed=parsed.failed,
        errors=parsed.errors,
        skipped=parsed.skipped,
        duration_seconds=parsed.duration_seconds,
    )


def _resolve_status(
    return_code: int,
    summary: AutomationRunSummary | None,
    timed_out: bool,
) -> str:
    if timed_out:
        return "timeout"
    if return_code != 0:
        return "failed"
    if summary and (summary.failed or summary.errors):
        return "failed"
    return "passed"


def _write_run_record(path: Path, record: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(record, ensure_ascii=False, indent=2), encoding="utf-8")


def _read_run_record(path: Path) -> dict[str, Any] | None:
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _duration_seconds(started_at: str, finished_at: str) -> float:
    started = datetime.fromisoformat(started_at)
    finished = datetime.fromisoformat(finished_at)
    return round((finished - started).total_seconds(), 3)


def _tail(text: str, max_chars: int = 5000) -> str:
    text = (text or "").strip()
    if len(text) <= max_chars:
        return text
    return text[-max_chars:]
